name: report_builder_repository
description: A Builder Package for handling Report creational process

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  veryf_detection_api:
    path: ../veryf_detection_api
  invoice_dataprovider:
    path: ../invoice_dataprovider
