name: veryf_detection_api
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  dio: ^4.0.6
  http: ^0.13.4
  http_parser: ^4.0.0
  mime: ^1.0.1
  path: ^1.8.0
  path_provider: ^2.0.9

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

flutter:
  assets:
    - assets/sample.jpg
    - assets/sample_cropped.jpg
    - assets/random_image.jpg
