name: user_dataprovider
description: Dart package which provide the user data
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  gsheets: ^0.3.2
  uuid: ^3.0.0
