name: report_repository
description: Dart package to manage report data from data provider
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  equatable: ^2.0.3
  latlng: ^0.1.0
  invoice_dataprovider:
    path: ../invoice_dataprovider
