name: report_dataprovider
description: Dart package for retrive report data from gsheet
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  
dependencies:
  gsheets: ^0.4.2
