name: veryf_storage
description: a package for veryf flutter to store invoice image
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  http: ^0.13.4
  http_parser: ^4.0.0
  mime: ^1.0.1
